### ISSUE TITLE
JasperReports 6.14.0 fails at Maven stage: "Could not find artifact com.lowagie:itext:jar:2.1.7.js8"

### ISSUE THREAD

**Issue by soc** [TIBCOSoftware/jasperreports#148]
When including jasper-reports in Maven as a dependency, Maven fails to resolve as it can't find `com.lowagie:itext:jar:2.1.7.js8`.

It seems as if JasperReports depends on a version of iText that is not available through public repositories.

**Comment by teodord** [comment]
Actually, this modified version of iText 2.1.7 is available on this public repository:
http://jaspersoft.jfrog.io/jaspersoft/third-party-ce-artifacts/com/lowagie/itext/2.1.7.js8/

Please note that the pom.xml of the JasperReports library has a repository entry for that:
```
<repository>
	<id>jaspersoft-third-party</id>
	<url>http://jaspersoft.jfrog.io/jaspersoft/third-party-ce-artifacts/</url>
</repository>

```
See it here:
https://github.com/TIBCOSoftware/jasperreports/blob/master/jasperreports/pom.xml#L522

**Comment by soc** [comment]
We are using JasperReports from MavenCentral directly, so that's probably why the `itext` artifact is not available.

Is it really necessary to depend on an additional repositories for dependencies of dependencies?
Wouldn't it be possible to publish it on Maven Central, like the rest of JasperReports?

**Comment by soc** [comment]
We are using JasperReports from MavenCentral directly, so that's probably why the `itext` artifact is not available.

Is it really necessary to depend on an additional repositories for dependencies of dependencies?
Wouldn't it be possible to publish it on Maven Central, like the rest of JasperReports?

**Comment by teodord** [comment]
We use a modified version of iText. It is not our own software and we modified it only under the terms of the LGPL license under which that version was published. It is not up to us to publish such modified version of iText in Maven Central repositories. 
We publish it in our own publish repositories. The solution is to simply add the jaspersoft.jfrog.io repository to your build files. The very fact that Maven allows custom repositories is testimony to the fact that using only Maven Central is not mandatory in a Maven ecosystem.

**Comment by soc** [comment]
Thanks for the help!

> We use a modified version of iText. It is not our own software and we modified it only under the terms of the LGPL license under which that version was published. It is not up to us to publish such modified version of iText in Maven Central repositories.

Would it be an option to use a current, maintained version of itext instead, or did the versions diverge too much?

>  The very fact that Maven allows custom repositories is testimony to the fact that using only Maven Central is not mandatory in a Maven ecosystem.

Granted, perhaps it's more of a fault of Maven Central that it accepts artefacts with missing dependencies.

> Another solution would be to exclude our modified iText from the JasperReports dependency in your build system and bring the original iText 2.1.7 from the Maven Central.

I guess another possibility would be to put the itext dependency in my Nexus manually?

**Comment by teodord** [comment]
Not sure what you mean by "current, maintained version of iText", because iText 2.1.7 is no longer maintained. We had to stay with it because after 2.1.7, iText changed its license.
The current version of iText is 7+, but since it has different package names inside, it acts like a total different library compared to 2.1.7, so you cannot use it as a replacement.
Again, you can use the original iText 2.1.7 from Maven Central, without our modifications, which are marginal and you probably don't need them. In order to do that, you would have to use <exclude> in your pom.xml when you bring JasperReports.
You can also use a different fork of the iText 2.1.7, which is called OpenPDF:
https://github.com/LibrePDF/OpenPDF

**Comment by soc** [comment]
Understood, thanks!

**Comment by mwithi** [comment]
> our modifications, which are marginal and you probably don't need them.

can you provide more information about those modification in jr8 version? Thanks!

**Comment by JD-CSTx** [comment]
> Actually, this modified version of iText 2.1.7 is available on this public repository:
> ```
> <repository>
> 	<id>jaspersoft-third-party</id>
> 	<url>http://jaspersoft.jfrog.io/jaspersoft/third-party-ce-artifacts/</url>
> </repository>
> ```

Depending on your setup and / or transitive dependencies this may be not enough, you may need this in <repositories> **_and_** also in <pluginRepositories> as:
<pluginRepository>
	<id>jaspersoft-third-party</id>
	<url>http://jaspersoft.jfrog.io/jaspersoft/third-party-ce-artifacts/</url>
</pluginRepository>

**Comment by fer-marino** [comment]
I'm getting this error:
```   > Could not resolve com.lowagie:itext:2.1.7.js8.
     Required by:
         project :pfd > net.sf.jasperreports:jasperreports:6.17.0
      > Could not resolve com.lowagie:itext:2.1.7.js8.
         > Could not parse POM http://jaspersoft.jfrog.io/jaspersoft/third-party-ce-artifacts/com/lowagie/itext/2.1.7.js8/itext-2.1.7.js8.pom
            > The element type "hr" must be terminated by the matching end-tag "</hr>".
```

I'm using gradle 6.8 and the repository mentioned above is in already

**Comment by DannyJaramil** [comment]
[ERROR] Failed to execute goal on project ride: Could not resolve dependencies for project com.rolandopalermo.fa
cturacion.ec:ride:jar:1.0.0: Failed to collect dependencies at net.sf.jasperreports:jasperreports:jar:6.4.0 -> c
om.lowagie:itext:jar:2.1.7.js5:

Me podrian ayudar ya importe :

<repository>
	       <id>jaspersoft-third-party</id>
	       <url>http://jaspersoft.jfrog.io/jaspersoft/third-party-ce-artifacts/</url>
      </repository>



pero continua apareciendo el error.

**Comment by teodord** [comment]
I think you need to use HTTPS for the URL nowadays:
https://jaspersoft.jfrog.io/jaspersoft/third-party-ce-artifacts/

See we are using HTTPS in our pom.xml:
https://github.com/TIBCOSoftware/jasperreports/blob/master/jasperreports/pom.xml#L540

**Comment by kareemradwan** [comment]
I fix this issue by exclude the **_com.lowagie.text_** from jasperReport library and add it as other library 
```

<dependency>
   <groupId>net.sf.jasperreports</groupId>
   <artifactId>jasperreports</artifactId>
   <version>6.16.0</version>

   <exclusions>
      <exclusion>
         <groupId>com.lowagie</groupId>
         <artifactId>itext</artifactId>
      </exclusion>
   </exclusions>
</dependency>


<dependency>
   <groupId>com.lowagie</groupId>
   <artifactId>itext</artifactId>
   <version>[1.02b,2.1.7]</version>
   <scope>compile</scope>
</dependency>

```

**Comment by teodord** [comment]
Not sure what you mean by _"JExcelApiExporter this class is not even included in my project"_.
You are probably upgrading from a JRL version older than 6.4.3, when the JExcel based exporter has been removed from our library.
The error indicates your application somehow references it, so you need to check that out.

I hope this helps.
Teodor

PS: Ideally, you should first post on the discussion forums at https://community.jaspersoft.com/project/jasperreports-library/answers, because this is not a bug and because it does not have anything to do with the current tracker you added your comment to.

**Comment by han4219** [comment]
> I fix this issue by exclude the **_com.lowagie.text_** from jasperReport library and add it as other library
> 
> ```
> 
> <dependency>
>    <groupId>net.sf.jasperreports</groupId>
>    <artifactId>jasperreports</artifactId>
>    <version>6.16.0</version>
> 
>    <exclusions>
>       <exclusion>
>          <groupId>com.lowagie</groupId>
>          <artifactId>itext</artifactId>
>       </exclusion>
>    </exclusions>
> </dependency>
> 
> 
> <dependency>
>    <groupId>com.lowagie</groupId>
>    <artifactId>itext</artifactId>
>    <version>[1.02b,2.1.7]</version>
>    <scope>compile</scope>
> </dependency>
> ```

it worked for me

**Comment by ishaqhaj** [comment]
JasperReports 6.10.0 transitively depends on com.lowagie:itext:2.1.7.js7, a Jaspersoft fork of the old iText library. That artifact is not on Maven Central; it only lives on Jaspersoft's JFrog repo (jaspersoft.jfrog.io).
Maven 3.8.1+ ships with a built-in **maven-default-http-blocker mirror** that **blocks** all plain http:// repositories for security. The Jaspersoft repos that JasperReports 6.10.0 declares are http://, so Maven refuses them. That's why nothing downloads.

Add the Jaspersoft repo over HTTPS in your pom.xml 
Jaspersoft's JFrog endpoint also works over https://. Just declare it explicitly and Maven's HTTP blocker is bypassed (because it's HTTPS, not HTTP). Add this to your pom.xml

```
<repositories>
    <repository>
        <id>jaspersoft-third-party</id>
        <url>https://jaspersoft.jfrog.io/jaspersoft/third-party-ce-artifacts/</url>
    </repository>
    <repository>
        <id>jr-ce-releases</id>
        <url>https://jaspersoft.jfrog.io/jaspersoft/jr-ce-releases</url>
    </repository>
</repositories>
```
