### ISSUE TITLE
Allow dynamic width on CrossTab columns or stretch columns based on content width.

### ISSUE THREAD

**Issue by mayankX** [TIBCOSoftware/jasperreports#19]

**Comment by teodord** [comment]
We need more details about this feature request. Crosstabs cells are meant to stretch vertically, just like any other text field that has isStretchWithOverflow="true".
If a text field is supposed to stretch horizontally, this is probably because the text needs to stay on a single row and do not wrap on a second row. Is that what you are trying to say?

**Comment by teodord** [comment]
Feel free to reopen if you can provide more details about the way you think is should work.

**Comment by devendra1988** [comment]
Please help regarding CrossTab Report Colums width not full page width please see attachment
[reportWardWiseList.pdf](https://github.com/TIBCOSoftware/jasperreports/files/3103325/reportWardWiseList.pdf)
