### ISSUE TITLE
India Rupee (₹) symbol not showing while export .jrxml to pdf format

### ISSUE THREAD

**Issue by syadavdev** [TIBCOSoftware/jasperreports#235]
<p>
I am using <code>JasperExportManager.exportReportToPdfStream</code> to generate report in pdf format but didn't get the rupee symbol in result pdf.
</p>
<p>
 Also tried many <b>.tiff</b> file to display rupee symbol in pdf format and search many solution none of them are working.
</p>
<p>
  pls provide a working solution for this.
</p>

**Comment by teodord** [comment]
I think you mean TTF files, not TIFF files.
You need a font file that supports this character and you need to make sure the TTF file is embedded into the PDF.
You would need to package it as a font extension JAR and deploy it with your application. Jaspersoft Studio has a wizard for creating font extensions for JasperReports.

I hope this helps.
Teodor

**Comment by syadavdev** [comment]
<p>Sry my bad, yes i mean TTF file ,i recently used this TTF : <a href="https://techwelkin.com/download/rupee-symbol-font/ITF-Rupee.ttf" rel="nofollow noreferrer">ITF-Rupee.ttf</a> </p>

<p>Can you share a sample in pdf file format with ₹ symbol in it ? , that will be very big help for me</p>

Thanks for reply
Teodor

**Comment by teodord** [comment]
I have tested the Unicode U+20B9 character (rupee) with the /demo/samples/unicode sample in the JasperReports project distro and it seems to work if you use the Noto font set.
You can download the project distro or get it from github and you can find this sample and run it with Ant + Ivy.
https://github.com/TIBCOSoftware/jasperreports/tree/master/jasperreports/demo/samples/unicode

This means that one of the TTF files that are part of this Noto font set that we defined in the sample does support the rupee character and it automatically gets used.
The solution for you is to use a font set when you define the font to be used by your text fields, because font sets can group multiple TTF files that support different languages and character sets. This way you could create a font set that supports both English, Indian scripts and the rupee character all grouped under a single font set name to use as font name in your report.
Our Noto font set in the sample does not seem to support English, but that is just a sample we made, you would be defining your own font set with the TTF files and languages that you want to cover.

I hope this helps.
Teodor
