### ISSUE TITLE
StretchHeight for TextField crops text in case of Excel/Word

### ISSUE THREAD

**Issue by danielpeintner** [TIBCOSoftware/jasperreports#245]
Hi,

I noticed a bug when using a `TextField` with `textAdjust="StretchHeight"` and Word/Excel export.

see snippet

```
<textField textAdjust="StretchHeight" isBlankWhenNull="true">
	<reportElement x="10" y="0" width="240" height="12" isRemoveLineWhenBlank="true" uuid="ce9c9ac7-8fe5-490c-a12f-3967944806bf"/>
	<box topPadding="0" leftPadding="0" bottomPadding="0" rightPadding="0">
		<topPen lineWidth="0.0" lineStyle="Solid" lineColor="#000000"/>
		<leftPen lineWidth="0.0" lineStyle="Solid" lineColor="#000000"/>
		<bottomPen lineWidth="0.0" lineStyle="Solid" lineColor="#000000"/>
		<rightPen lineWidth="0.0" lineStyle="Solid" lineColor="#000000"/>
	</box>
	<textElement textAlignment="Left" verticalAlignment="Middle" markup="none">
		<font size="10" isBold="false"/>
	</textElement>
	<textFieldExpression><![CDATA[$F{wertLinks}]]></textFieldExpression>
</textField>
```

The TextField gets properly layouted with PDF Export.

![grafik](https://user-images.githubusercontent.com/11281461/147060761-3a8bd616-8166-4112-b74d-9c7ce4ff419d.png)

Having said that, if I use Excel or Word export the height seems somehow slightly wrong. It stretches the height to multiple lines but it seems a bit is missing space (since it is `middle`'d at the top and the bottom).

![grafik](https://user-images.githubusercontent.com/11281461/147060206-242d5942-9e1f-47ab-8872-750810ee944a.png)

Note: I use the default font DejaVu Sans which is also shown correctly in Excel/Word export.

Is this a known issue. Is there anything special I need to respect for Excel/Word export.
Thanks for any feedback and  thank you for all your hard word!

**Comment by teodord** [comment]
The Excel and Word exports are not as pixel-perfect as AWT (Java) and PDF.
That is because of several reasons. For example, in Excel, there is no way to control line spacing, which means whatever default line spacing Excel uses would not perfectly match what we have in Java and PDF for a given font name and font size.

For Excel export, there is this setting that might help:
http://jasperreports.sourceforge.net/config.reference.html#net.sf.jasperreports.export.xls.font.size.fix.enabled
