### ISSUE TITLE
CVE-2022-23302/23305/23307 

### ISSUE THREAD

**Issue by Dopmo** [TIBCOSoftware/jasperreports#250]
CVE-2022-23302/23305/23307 is a high-risk vulnerability of the log4j 1.X series. We analyzed the pom files of jasperreport 6.11.0 and 6.16.0 and used log4j 2.8.2. I want to check whether the two versions are not affected by the vulnerability.

Thanks in advance

**Comment by teodord** [comment]
If you analyzed the pom files, you probably saw that they have scope=test for the Log4j dependencies, meaning they are used when running the tests and not when compiling the JasperReports library.
JasperReports does not actually require or use Log4j. It uses Apache Commons Logging. That one is indeed a requirement.

Even if JasperReports would have used and required Log4J, it would still not make sense to talk about old releases. Because CVEs are always dealt-with simply by upgrading. We never go back fix old releases. We only release new ones.
