### ISSUE TITLE
Functions: Replace Joda Time with Java 8 Time API

### ISSUE THREAD

**Issue by daniel-shuy** [TIBCOSoftware/jasperreports#256]
`jasperreports-functions` still depend on the Joda Time library. Since `jasperreports-functions` has been migrated to Java 8, it is better to migrate it to use the Java 8 Time API instead and remove the dependency on Joda Time library altogether.

I have begun the work to do so, but looks like is it not as straightforward as expected, there are some discrepancies between the behaviors of Joda Time and Java 8 Time API.

For example, Joda Time's `DateTimeFormat` will skip the timezone ID symbol if the timezone is not available (eg. formatting a `LocalTime`), whereas Java 8's `DateTimeFormatter` will throw an error (even if the [ResolverStyle](https://docs.oracle.com/javase/8/docs/api/java/time/format/ResolverStyle.html) changed to `LENIENT`), eg.
```java
Locale.setDefault(Locale.US);

System.out.println(
    org.joda.time.LocalTime(12, 34, 56)
        .toString(org.joda.time.DateTimeFormat.longTime()));
// 12:34:56 PM 

System.out.println(
    java.time.format.DateTimeFormatter.ofLocalizedTime(java.time.format.FormatStyle.LONG)
        .format(java.time.LocalTime.of(12, 34, 56)));
// java.time.DateTimeException: Unable to extract ZoneId from temporal 12:34:56 with chronology ISO
```
In most Locales, the **long** time style is identical to the **medium** time style, but there are certain Locales where they differ, eg.
```java
Locale.setDefault(Locale.KOREA);

System.out.println(
    org.joda.time.LocalTime(12, 34, 56)
        .toString(org.joda.time.DateTimeFormat.longTime()));
// 오후 12시 34분 56초 

System.out.println(
    java.time.format.DateTimeFormatter.ofLocalizedTime(java.time.format.FormatStyle.MEDIUM)
        .format(java.time.LocalTime.of(12, 34, 56)));
// 오후 12:34:56
```
Alternately, a timezone can be passed to `DateTimeFormatter`, eg.
```java
System.out.println(
    java.time.format.DateTimeFormatter.ofLocalizedTime(java.time.format.FormatStyle.LONG)
        .withZone(java.time.ZoneOffset.UTC)
        .format(java.time.LocalTime.of(12, 34, 56)));
// 오후 12시 34분 56초 Z
```
But the timezone ID will be included in the String returned from the `TIME()` function.

Will it be acceptable to introduce such breaking changes?

Also, will it be ok for me to add unit tests to `jasperreports-functions` using JUnit 5 and AssertJ? (there are currently no unit tests for `jasperreports-functions`)

**Comment by maxrabbi** [comment]
Hi, thanks for reporting on this.
We did some code changes to the DateTimeFunctions class in order to get rid of the Joda time library dependency.

As you mentioned the possible problematic part could be the datetime formatting one, in particular the TIME( ) function.
That said, we discussed a bit and think that the "breaking changes" are acceptable. After all that part was not correctly handling report locale and timezone already. 

The new outputs appear to be more correct. I'm attaching a bunch of screenshots of some report runs with different locale/timezon combinations. 
If you have other "corner" use cases you thought about please let us know.
Thanks again!

Regards,
Massimo.

![korean_sample_datetime_functions](https://user-images.githubusercontent.com/26139741/157261548-a1b176f9-3b94-4500-94ac-4afa17098a54.png)
![hawaiian_sample_datetime_functions](https://user-images.githubusercontent.com/26139741/157261557-2fa7c610-20b5-4cd3-bae4-42b8d8b90bb8.png)
![arabicegypt_sample_datetime_functions](https://user-images.githubusercontent.com/26139741/157261560-893d2eb2-dba1-4a6d-acfc-f5c8440ab50b.png)
![israeli_sample_datetime_functions](https://user-images.githubusercontent.com/26139741/157261564-931838cd-7fbd-4399-8896-4804211be325.png)
![italian_sample_datetime_functions](https://user-images.githubusercontent.com/26139741/157261570-e1107dab-9876-4fb8-8333-d69c24810a54.png)
![chinese_sample_datetime_functions](https://user-images.githubusercontent.com/26139741/157261574-fb61a199-3b3a-429e-87ee-e0b466895d71.png)

**Comment by daniel-shuy** [comment]
@maxrabbi Nice! Glad to hear that there is already work being done on replacing Joda Time with the Java 8 Time API. Looking forward to it.

From what I see, the new output for the `TIME()` function simply appends the timezone ID of `REPORT_TIME_ZONE` to the formatted timestamp. I'm just wondering if additional functions should be provided to convert from `UTC to `REPORT_TIME_ZONE`, since timestamps are usually stored in `UTC`, not local time.

**Comment by daniel-shuy** [comment]
@maxrabbi sorry, my explanation was slightly incorrect. For most locales, `FormatStyle.LONG` usually includes the timezone ID, therefore the `TIME()` function usually has the same effect as including the timezone ID with the formatted timestamp.

I was just wondering if there should be additional functions/overloads to convert from `UTC` to `REPORT_TIME_ZONE`, since timestamps are usually stored as `UTC`. But never mind, it's probably safer to do the conversion (eg. `Instant` to `ZonedDateTime`) in the application itself, and I'd rather not delay this further.

**Comment by teodord** [comment]
New snapshot JAR from master branch available here:
https://jaspersoft.jfrog.io/ui/native/jr-ce-snapshots/net/sf/jasperreports/jasperreports-functions/master-SNAPSHOT/
