### ISSUE TITLE
isRemoveLineWhenBlank + printWhenExpression leaves whitespace at the end of the page

### ISSUE THREAD

**Issue by zimmi** [TIBCOSoftware/jasperreports#276]
Hi there!

I ran into a problem where whitespace of elements removed via `isRemoveLineWhenBlank` and `printWhenExpression`  seems to accumulate at the bottom of each page. It is particularly noticeable in our report because there are many optional elements / lines.

Here is a minimal test case to reproduce the problem:
The report contains three colored `Frame`s, each filling half the page, the first one hidden via `isRemoveLineWhenBlank` + `printWhenExpression`.

**Expected**
A single page PDF is generated, containing the second and third `Frame` with no space in between.

**Actual**
A two page PDF is generated with the space occupied by the first removed `Frame` occupying the space at the end of the first page.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Created with Jaspersoft Studio version 6.19.1.final using JasperReports Library version 6.19.1-867c00bf88cd4d784d404379d6c05e1b419e8a4c  -->
<jasperReport xmlns="http://jasperreports.sourceforge.net/jasperreports" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd" name="trailing_whitespace" pageWidth="595" pageHeight="842" columnWidth="595" leftMargin="0" rightMargin="0" topMargin="0" bottomMargin="0" uuid="f782ae36-77d8-4547-b8dc-40fa98a8c83d">
	<property name="com.jaspersoft.studio.data.defaultdataadapter" value="One Empty Record"/>
	<queryString>
		<![CDATA[]]>
	</queryString>
	<detail>
		<band height="842" splitType="Stretch">
			<frame>
				<reportElement positionType="Float" x="0" y="0" width="595" height="842" uuid="bb014fc8-e288-4a4e-9609-02d9fd9ed262"/>
				<frame>
					<reportElement positionType="Float" mode="Opaque" x="0" y="0" width="595" height="421" isRemoveLineWhenBlank="true" backcolor="#FF0000" uuid="26b35b37-b5fd-486a-a82d-98dc099a26a0">
						<printWhenExpression><![CDATA[false]]></printWhenExpression>
					</reportElement>
				</frame>
				<frame>
					<reportElement positionType="Float" mode="Opaque" x="0" y="421" width="595" height="421" isRemoveLineWhenBlank="true" backcolor="#00FF00" uuid="3d8fb615-4243-415b-b1cd-cefdd284252c"/>
				</frame>
				<frame>
					<reportElement positionType="Float" mode="Opaque" x="0" y="842" width="595" height="421" isRemoveLineWhenBlank="true" backcolor="#0000FF" uuid="60a0a35b-0682-4436-84cd-05e93156e754"/>
				</frame>
			</frame>
		</band>
	</detail>
</jasperReport>
```

This is with JasperReports 6.19.1 and openjdk 11.0.15 2022-04-19.

Please let me know if you need further information.

**Comment by teodord** [comment]
Hi,

The report behaves as designed and this is usually an issue with large bands/frames such as the ones you have.

The reasons is that the engine first expands elements and lays them out according to their relative size and positions, while the cleanup of white space resulting from elements that did not render is collapsed only after that. This process happens for the band/frame as a whole and what you expect would only be possible if the bands/frames would be processed in smaller chunks.

Having said that, the solution is to split large bands into smaller ones, that can be processed independent of one another, allowing the layout engine to cleanup white space right there where it occurs, instead of being a later event that occurs too late, after the page break has already been introduced.

If you put each frame in its own band (there can be multiple detail bands in a report), the engine would already know that the first red frame did not print and the current rendering position did not advance.

Now, in your particular case, the 3 colored frames are put together in a parent frame. The use of a parent frame is usually needed if you want to put a border around them all, but in your case there is no styling for the parent frame, so I am not sure why it is used for.
In case you do need a parent frame, note that the parent frame can be made small and the children frames can actually go beyond the parent frame bottom edge. Also, note that frame can expand vertically to match the height of their content, so just by making frames smaller at design time, you can avoid them causing unnecessary page breaks just by their huge initial heights. If they are made small at design time, they would then grow at runtime only as much as needed and premature or unnecessary page breaks would be avoided.

I hope this helps.
Teodor

**Comment by zimmi** [comment]
Hi @teodord,

thank you for taking the time to answer! I tried your suggestion and it works flawlessly, i.e. the following template creates the desired single page PDF:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Created with Jaspersoft Studio version 6.19.1.final using JasperReports Library version 6.19.1-867c00bf88cd4d784d404379d6c05e1b419e8a4c  -->
<jasperReport xmlns="http://jasperreports.sourceforge.net/jasperreports" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd" name="trailing_whitespace" pageWidth="595" pageHeight="842" columnWidth="595" leftMargin="0" rightMargin="0" topMargin="0" bottomMargin="0" uuid="f782ae36-77d8-4547-b8dc-40fa98a8c83d">
	<property name="com.jaspersoft.studio.data.defaultdataadapter" value="One Empty Record"/>
	<queryString>
		<![CDATA[]]>
	</queryString>
	<detail>
		<band height="421" splitType="Stretch">
			<printWhenExpression><![CDATA[false]]></printWhenExpression>
			<frame>
				<reportElement positionType="Float" mode="Opaque" x="0" y="0" width="595" height="421" backcolor="#FF0000" uuid="26b35b37-b5fd-486a-a82d-98dc099a26a0"/>
			</frame>
		</band>
		<band height="421" splitType="Stretch">
			<frame>
				<reportElement positionType="Float" mode="Opaque" x="0" y="0" width="595" height="421" backcolor="#00FF00" uuid="3d8fb615-4243-415b-b1cd-cefdd284252c"/>
			</frame>
		</band>
		<band height="421" splitType="Stretch">
			<frame>
				<reportElement positionType="Float" mode="Opaque" x="0" y="0" width="595" height="421" backcolor="#0000FF" uuid="60a0a35b-0682-4436-84cd-05e93156e754"/>
			</frame>
		</band>
	</detail>
</jasperReport>
```

The parent frame in the original template was there because bands never shrink below their initial height, but the total height of all the children was 1.5x the page size, so setting the band height to 1.5x page size would always ensure trailing white space. Having the frame of 1x page size around everything (and band size accordingly) was essentially an attempt to trick the engine into not expanding the detail band past the actual frame height, which should have been 1x page size with one of the children not rendered. At least that was my thinking of how things worked, but you cleared that up, thanks again.

So the general rule of thumb seems to be: Whenever there are optional lines, put them in separate detail bands to avoid unnecessary page breaks. Correct?

Regards,
Thomas

**Comment by teodord** [comment]
Hi,

Yes, the rule of thumb would be: wherever there is a place where page could break, split it at design time there into separate bands, to help the engine doing optimal layout at runtime. Avoid large bands and split them in places it is acceptable for the content to have page breaks.

Also, in case of frames, keep them small knowing that they will stretch in height anyway, if their content inside is bigger then their design height.

I hope this helps.
Teodor
