### ISSUE TITLE
Appending QR encoding when not necessary breaks old readers

### ISSUE THREAD

**Issue by Canos** [TIBCOSoftware/jasperreports#30]
After studying the QR engine at zxing we've found a bug with some readers when the ISO-8859-1 character set is being passed to the zxing library as hint.

The bug raised when some datalogic old readers can't detect the ECI (character encoding) coded in the QR, because (it's a guess) they only support ISO-8859-1 as you can see at #11. 

Zxing only add the ECI header when the hint is passed, so the solution would be to only send the character encoding hint when it's different than the default (ISO-8859-1).  That means adding to `QRCodeSVGImageProducer` something like that:

```
# Preventing add the ECI header when not necessary
if(!encoding.equals("ISO-8859-1"))
  hints.put(EncodeHintType.CHARACTER_SET, encoding);
```

**Comment by dadza** [comment]
Fixed by allowing empty values for the QR encoding property.  When the property is empty (like below), no character encoding hint is set on ZXing.

`net.sf.jasperreports.components.qrcode.character.encoding=`

Testing for ISO-8859-1 and ignoring it seemed a little arbitrary, empty property means that the no character encoding is set.  UTF-8 is still used by default.

**Comment by Canos** [comment]
Sorry but this solution dont solve the problem.

Despite the version of zxing that jasper is working on, in current (3.3) version of zxing, if hint is set (any value) set the ECI segment value an breaks the read. 
I file an issue about that in zxing  https://github.com/zxing/zxing/issues/1042

In order to maintain a stronger codebase that works with any version of zxing, i'd recomend to detect not only empty values, but default ISO-8859-1 values.

Thanks for fast anwser

**Comment by dadza** [comment]
I don't understand how ignoring ISO-8859-1 helps.  If you don't want a hint to be set, don't set the property to ISO-8859-1, leave it empty.

**Comment by srowen** [comment]
If an empty property causes it to not set the encoding hint, that should be fine IMHO. I'd suggest it should be the default. 

ISO-8859-1 is special in that it is the default that will be used if nothing is specified. It's worth considering special-casing it too. If you set that encoding as a hint you will generate an ECI segment in the QR code that isn't needed - takes up nontrivial extra space in the code. (In addition to maybe confusing a few readers out there.)

**Comment by dadza** [comment]
The default QR code encoding in JasperReports has been UTF-8 since version 6.0.2 (when QR code support was introduced).  We're going to keep UTF-8 as default for the sake of backward compatibility.

Treating ISO-8859-1 in the same way as an empty property seems like a loss of functionality to me.  If someone wants to use ISO-8859-1 but needs an ECI segment for some reason (I don't know if there are actual reasons for which someone would want that, so this is just a theoretical scenario), there would be not way to do it if ISO-8859-1 is ignored.  Allowing ISO-8859-1 offers more options than treating ISO-8859-1 and empty property in the same way.

**Comment by srowen** [comment]
Fair point. I also don't know of a reason one would do that. It makes the QR code slightly worse. But if it's not default behavior, only people who explicitly choose to insert the ECI segment anyway get that behavior.

**Comment by Canos** [comment]
I agree with you Dazda. 

In current jasper (who is using zxing 3.2.1) if you need ISO-8859-1 you must add the property 
`net.sf.jasperreports.components.qrcode.character.encoding` who is internaly setting a hint that's making the ECI segment will be inserted in zxing. 
That's what i am trying to prevent, some gun readers can't understand ECI segment and can't understand UTF-8.

I can see it's a very concrete issue with probably old devices, i've override the SVGImageProducer class, with the desired behavior ( and works like a charm to me.
