### ISSUE TITLE
Getting "null" from JasperFillManager.fillReport

### ISSUE THREAD

**Issue by tuspatil1** [TIBCOSoftware/jasperreports#306]
Hi Team,

We are using "jasperreports-6.19.0.jar" in our application & using "JasperFillManager.fillReport()" API to genarate the jasper print. One of our customer getting "null" as a return from this API on production environment. We need to understand why jasper library is returning "null".

Code Snippet: 
jasperPrint = JasperFillManager.fillReport(getJasperReport(report), reportParameters, jrDataSource);

Please let us know, if we have any mechanism to enable loggers of jasperreports library (community version) to analyse the root cause of this problem.

Thanks,
Tushar

**Comment by tuspatil1** [comment]
Hi Team,

Please suggest on this.

**Comment by tuspatil1** [comment]
Hi Team,

Please suggest on this.

**Comment by tuspatil1** [comment]
Hi Team,

We are eagerly wating for yor revert.

**Comment by teodord** [comment]
The JasperReports Library never returns null on that method call. If something goes wrong, an exception is raised (JRException).
The code snippet you gave above, with a single line of code, does not actually show what the application is doing with the possible exception raised by that call.

**Comment by tuspatil1** [comment]
Hi Teodor,

Please let us know, if we have any mechanism to enable loggers of jasperreports library (community version) to analyse the root cause of this problem.

Thanks,
Tushar

**Comment by dadza** [comment]
The first thing to look at is the full exception stacktrace, including nested exception/Caused by.. lines.  Please include the exception stacktrace here, it should show the exact place where the exception originates and provide clues on where to look for the root cause.

You can enable debug (or even trace) logging for net.sf.jasperreports in the logging library that you use in your project and, assuming that the logging library bridges to Apache Commons Logging API, you will see debug messages produced by JasperReports.

Regards,
Lucian

**Comment by dadza** [comment]
Please make sure that you log any exceptions that you catch in your code.  E.g. (with Apache Commons Logging):

```
try {
..
} catch (Exception e) {
    org.apache.commons.logging.LogFactory.getLog(getClass()).error("Exception", e);
}
```

**Comment by tuspatil1** [comment]
Hi Lucian,

We have already included "JasperFillManager.fillReport(..)" in try-catch block, but we observed that it is returning "null" & not thowing any exception.

Below is our code snippet:
          _try {
	          /**
	            * Some lines of code
	            *
	            */
	          try (ProfilePoint profilePoint = ProfilePoint
			          .profileActivity(PROFILE_JASPERREPORTEXECUTOR + "_jasperFillApiProfile")) {
		          jasperPrint = JasperFillManager.fillReport(getJasperReport(report), reportParameters,
				          jrDataSource);
	          }
          } catch (Exception e) {
	          logger.error("getJasperPrint(): Error While executing Jasper report", e);
	          e.printStackTrace();
	          throw e;
          }_

Thanks,
Tushar

**Comment by dadza** [comment]
When you say that JasperFillManager.fillReport returns "null", does it mean that the jasperPrint reference returned by the fillReport method call is null?

I don't see how that can happen.  If that's what you're experiencing, please create a minimal self contained test case in which JasperFillManager.fillReport returns null so that we can reproduce the behaviour and debug it.

Regards,
Lucian
