### ISSUE TITLE
missing dist and lib folder

### ISSUE THREAD

**Issue by charbel911** [TIBCOSoftware/jasperreports#310]
i've downloaded jasperreports 6.20.0 and add it to node js project and run it after that i received an error missing dist and lib folders please help me with it

**Comment by teodord** [comment]
Hi,

It is not clear to me what are you trying to do. Maybe you can provide more details.

Thanks,
Teodor

**Comment by charbel911** [comment]
i have created a jasper report in studio and save it as jrxml file now i want to use this file in node js i followed node-jasper npm package and in the configuration there is a path to jasperreports x-x-x directory so i've downloaded jasperreports 6.20.0 and added it to my node js project and i run the project it gaves me lib folder not found i know that jasperreports project contains 2 folders lib and dist and they are not included when i downloaded it from jasper report community

**Comment by teodord** [comment]
You might want to contact the authors of the node-jasper project, which I am not familiar with.
What I can tell you is that the JasperReports Library project distro no longer has a /lib folder since the 6.2.1 release made back in March 2016.
If you want to generate reports using JasperReports engine from a different platform such as Node, you could try the JasperReports IO project which exposes a REST API to run reports and you could make REST calls from Node.
JasperReports IO is a reporting service:
https://community.jaspersoft.com/project/jasperreports-io
It is not open source, though.
