### ISSUE TITLE
How to change single element properties without fire PropertyChange?

### ISSUE THREAD

**Issue by pandabai** [TIBCOSoftware/jasperreports#311]
in jrxml file , i put a textfiled in detail band , by giving a list of data ,it will repeat many times which make it like a table;
after code  
`JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, param, new JRBeanCollectionDataSource(mainReportBeanList));
`,  got jasperPrint,
 i need to change some element propertis in jasper print , like box-BottomPen,but when i setLine, it have to firePropertyChange,
every element change for the same. just need to change the last element in every page.
any way to avoid fire that?
that will help a lot!!!

**Comment by teodord** [comment]
The problem with trying to modify elements in the generated JasperPrint object is that their properties are consolidated and shared across multiple other elements that originate from the same report design element. So when you modify the border of one such element, you actually modify the border that all elements originating from the same design element share.

One way to get rid of this style properties consolidations that occurs during the report filling process when the JasperPrint object is created is to process the JasperPrint by exporting it to XML and importing it back.
When imported back from XML, the elements inside the resulting JasperPrint object no longer share the style properties and each of them has a copy of those properties.

You export the JasperPrint object to XML using the JRXmlExporter and you import it back using the JRPrintXmlLoader.

As for the property change events, you are affected by this mechanism only if you have listener objects listening to such property change events. If you do not listed to these events, they fire, but nothings actually happens, so I don't see what the problem is with them.

**Comment by pandabai** [comment]
> 
Thank for your xml method and explaining!
