### ISSUE TITLE
Publish jasperreports-chart-themes to Maven

### ISSUE THREAD

**Issue by asfernandes** [TIBCOSoftware/jasperreports#32]
This library has only an old version (5.1.0) published.

**Comment by teodord** [comment]
The optional JRL artifacts are published on jaspersoft.jfrog.io:

https://jaspersoft.jfrog.io/jaspersoft/jr-ce-releases/net/sf/jasperreports/jasperreports-chart-themes/

**Comment by asfernandes** [comment]
Why not publish on central?

**Comment by dsmorse** [comment]
I noticed that the release pages:
https://community.jaspersoft.com/project/jasperreports-library/releases 
https://github.com/TIBCOSoftware/jasperreports/releases/tag/jr-6-7-0

include two jars which are not in the above listed repo:
Fonts:  https://jaspersoft.jfrog.io/jaspersoft/jr-ce-releases/net/sf/jasperreports/jasperreports-fonts/
JasperReports: https://jaspersoft.jfrog.io/jaspersoft/jr-ce-releases/net/sf/jasperreports/jasperreports/

Are the 6.7.0 artifacts going to get published there?

**Comment by teodord** [comment]
David, I assume you refer to the jasperreports-fonts and jasperreports-javaflow optional artifacts.

More recent releases of the fonts artifact exist on central repositories.
We do not publish it with every release because for a long time now the package is virtually unchanged.
Indeed, we offer new versions for download on the pages you mentioned, but just so that people see it is available as extension.

As for the Javaflow JAR, this is a specially instrumented version of the JRL main JAR that is useful in certain deployments where multi-threading is an issue. In normal circumstances, people should not need to use this one. This is not an add-on, but rather a replacement for the main JAR. We did not publish it through Maven as it is rarely used and did not want to make it too much confusing for people looking for the JRL artifact.

**Comment by dsmorse** [comment]
What is the URL to central repo that the the most up to date jars?    I ask because it has led to some confusion with my devs as they can download a 6.7.0 fonts from the product release page, but I can not find it in a maven repo to fetch the artifacts.

Thank you for the info about the javaflow, but I was actually referring to the main jasperreports jar which only shows 6.4.31 as the latest version

**Comment by teodord** [comment]
The central Maven repo is at:
https://repo1.maven.org/maven2/net/sf/jasperreports/

The releases of JRL found on jaspersoft.jfrog.io artifactory are made for internal use in TIBCO products. They are mostly fixes made on top of older releases. For the open source community, we never fix older releases, but rather make new releases having the fixes.

**Comment by asfernandes** [comment]
The last version in central is still 5.1.0. As this issue was closed, I guess the next version is prepared to be published there, right?

**Comment by teodord** [comment]
Adriano, you are talking about version 5.1.0 of which artifact? Can you show me the link you are looking at on central repos?

**Comment by asfernandes** [comment]
JasperReports latest version is published in https://mvnrepository.com/artifact/net.sf.jasperreports/jasperreports

jasperreports-chart-themes (this issue subject) is published in https://mvnrepository.com/artifact/net.sf.jasperreports/jasperreports-chart-themes only with 5.1.0 version, which is obviously outdated.

**Comment by teodord** [comment]
We do not know who mvnrepository.com is and who manages its contents. We certainly never published anything on that website. So you should contact them to see why they have only version 5.1.0 there.
I repeat, all our JRL optional artifacts are all found at:
https://jaspersoft.jfrog.io/jaspersoft/list/jr-ce-releases/net/sf/jasperreports/
