### ISSUE TITLE
How to pass HTTP headers with JsonDataSource()

### ISSUE THREAD

**Issue by tuspatil1** [TIBCOSoftware/jasperreports#327]
Hi Team,

We are using `JsonDataSource​(String location, String selectExpression)` API  to executing the REST URL. We need to pass HTTP headers for executing the REST URL.

We are forming expression as follow.
`new net.sf.jasperreports.engine.data.JsonDataSource("http://xyz.xyxnet.xyx.com:2280/Windchill/trustedAuth/servlet/odata/D...","value") `

But this particular endpoint expects some header information from requestor like `("Accept", "application/json")` else it throws bad exception as error, is there any way we can pass header info here.

Your early response will be very helpful.

Thanks,
Tushar

**Comment by teodord** [comment]
Hi,

Access to remote resources using simple URLs like this does not allow customizing the requests.

However, when JSON data is retrieved from a remote location through HTTP, a data adapter can be used, instead of instantiating the JsonDataSource object.

Here is a screenshot from Jaspersoft Studio, which shows a JSON data adapter editor and we can see it offers the possibility to configure request headers:

![image](https://user-images.githubusercontent.com/2511035/221027889-6cae2b79-353c-4b2c-9209-0496f7b130ba.png)

I hope this helps.
Teodor
