### ISSUE TITLE
Space to separate thousands from numbers with jdk17

### ISSUE THREAD

**Issue by gbouget** [TIBCOSoftware/jasperreports#334]
Hello,

Why the space to separate thousands from numbers is not displayed with java 17 but works with java 11? In POM, I generate a jasper file (JasperReport) from jrxml (JasperDesign) with version 6.20.0.

jrxml :
```XML
<textField>
  <reportElement x="0" y="30" width="440" height="30" uuid="d1ad1c28-1603-48bb-adaf-f86bd03d0113"/>
  <textFieldExpression><![CDATA[NumberFormat.getInstance(new Locale.Builder().setLanguage("fr").setRegion("FR").build()).format(DOUBLE_VALUE("122811.18"))]]></textFieldExpression>
</textField>
```

PDF generated with jdk11 
![image](https://user-images.githubusercontent.com/12697930/221920326-71a83a38-9b80-46c9-85d7-4d7a9e5bfe60.png)

Output with jdk 17.0.2
![image](https://user-images.githubusercontent.com/12697930/221920430-ca80ad97-f6dc-45b8-b806-aff278a64555.png)

**Comment by dadza** [comment]
That's because the thousands separator for the French locale has changed in Java 17 from a regular space (U+00A0) to a Unicode NARROW NO-BREAK SPACE (U+202F).  See for instance https://bugs.openjdk.org/browse/JDK-8274768

The Helvetica font which is used by default for PDF doesn't have a glyph for U+202F, so the character is not displayed.

You need to use an embedded PDF font (from a font extension) that includes a glyph for U+202F.  For instance DejaVu Sans from the font extension shipped with JasperReports (https://central.sonatype.com/artifact/net.sf.jasperreports/jasperreports-fonts/6.20.0).
