### ISSUE TITLE
Is there a way to programmatically edit  .jrxml files using any core methods.

### ISSUE THREAD

**Issue by Sahilshetye** [TIBCOSoftware/jasperreports#336]
I have an use case of changing `<staticText>` element to  `<textField>` element in 10-15 jrxml files. Each file has about 100-200 `<statictext>` elements. I was hoping to write a quick method  to edit  xml node and  save them as `<textField>` element.  I used the  internal `javax.xml.parsers.DocumentBuilder` xml parser to read and edit the file. But I am having trouble in  writing it back into jrxml.  I was hoping there is a way to to use the JRXMLoader in some way to edit the existing `.jrxml` files and write using JRXMLWriter.

I could not find a simpler way to do the same in JasperStudio

**Comment by teodord** [comment]
Hi,

You might want to take a look at the report updater sample which uses an Ant task to bulk-modify many JRXMLs placed in a folder structure, using an updater program that implements a simple interface:
https://jasperreports.sourceforge.net/sample.reference/antupdate/index.html#antupdate

To post questions about JasperReports, please use the public forums at:
https://community.jaspersoft.com/project/jasperreports-library/answers
instead of opening issues here, which are used mostly for reporting bugs.

Thank you,
Teodor

**Comment by Sahilshetye** [comment]
Actually I had a great success in using  
 `Document doc = JRXmlUtils.parse(file);` to  get the doc to manipulate as xml and writing it back using normal Transmformer to generate jrxml. But I had to edit and save the jrxml in Studio to apply the correct grammar for the jrxml.
 Closing the issue as per your feedback. Thank you.
