### ISSUE TITLE
PDF: Band height results into either an extra blank page, or infinite loop if band goes exactly till the end of the current page

### ISSUE THREAD

**Issue by warm-ice** [TIBCOSoftware/jasperreports#374]
Not getting expected pdf output when the band goes exactly till the end of the current page.

If height is exactly the sum of inner elements, it results into an extra empty page after the data.
If height is more than the sum of inner elements, it results into infinite loop.

Attaching a demo project to reproduce the problem.
File src/main/resources/school.jrxml 
I have added comments at line# 19, and the band starts at line# 23 after the comments.

```
height = 104 # results into extra empty page before next band
height = 105 # will not generate pdf

```
to run the pdf generation 
```
mvn clean compile jasperreports:jasper exec:java
```
or run with
```
bash test.sh
```
It will generate output/document.pdf.

[printing.zip](https://github.com/TIBCOSoftware/jasperreports/files/11865542/printing.zip)

**Comment by teodord** [comment]
Hi,

Thank you for providing an easy to test case.

It confirms what I was suspecting from the beginning:

When an infinite look occurs, the #1 suspect is the flag isPrintWhenDetailOverflow="true". You have it set on the on the "grade" subreport inside the "school" template.
Are you sure you want it this way? It means that when parent band of "grade" subreport element overflows onto a new page, for whatever reason, the "grade" subreport would need to be rendered all over again, in case it is not it that caused the page break in the first place.

Now, you might wonder, why is the grade parent band overflowing onto a new page since everything seems to fit perfectly.
Well, it just happens that you left a 1 pixel gap at the end of the band, below the grade subreport element.
It is precisely that pixel that does not fit and gets "renderer" onto a new page.
The band "overflows" with white space, as we call it.
If you ask: "why does the engine overflows with white space?".
The engine preserves all white space you put in your design. If you do not want that white space of 1 pixel, then why do you put it there?

So there are two ways to solve your report, which considering all the explanation above, is considered invalid.
Just think about it: the band overflows because 1 pixel of white space did not fit. On the new page, the grade subreport needs to appear again, because of isPrintWhenDetailOverflows=true. And then it goes to the bottom of the page where the pixel does not fit again, and again, and again....

Such situations cannot be detected at report design time, because you see they depend on runtime data as well, like in your case, the number of records in the grade subreport.

I hope this helps.
Teodor
