### ISSUE TITLE
Text not recognised as html despite setting markup to html

### ISSUE THREAD

**Issue by SofieYesplan** [TIBCOSoftware/jasperreports#385]
Summary of issue:

While working with library version 6.20 we encountered a problem when generating reports that print html via text fields.
We noticed whitespaces being printed in text fields where markup was set to html while we expect this to remove the whitespace.
We've prepared an example report with 3 cases to illustrate the problem. This problem does not occur in version 6.17 so the issue must have appeared somewhere between then and 6.20.

This is how we constructed the test report:

We made 3 examples of text printing

1. In the left column plain text is printed as a reference.
2. In the middle column the text field should print html as Markup is set to html. However, this is not the case and the spacing still gets printed.
3. In the third column we show that the text field **does** show expected behavior of printing html when a html tag is added to the input of the text field. Which tag is irrelevant, as this works with things like < b > but also < br/ > ...

This is not a workaround because we cannot simply change the input data of our reports to always contain some html tags, we just want the spacing to be ignored as it should be when markup is set to html.
[htmltest.jrxml.zip](https://github.com/TIBCOSoftware/jasperreports/files/12358632/htmltest.jrxml.zip)

**Comment by teodord** [comment]
This is a side effect of an optimisation made with this occasion:
https://github.com/TIBCOSoftware/jasperreports/issues/236
The idea is that we try to process HTML content only if the text contains at least some HTML tag in it and is not just pure text.

Your text seems to be pure text without any HTML tag in it. If you want the empty space to be removed, then add a harmless empty P tag at the beginning of your text content like this:

`<textFieldExpression>"<p/>" + $F{MyHtml}</textFieldExpression>`

**Comment by SofieYesplan** [comment]
Sadly, as I mentioned at the end of the text above this is not a proper workaround for our situation. Our clients fill in these fields themselves on their installation of our product and we cannot expect them to always include html tags. They are users that often have no knowledge of html or basic computer science in general. I understand the reasoning though, so we'll look into finding a workable solution for our specific situation. Thanks for the reply!

**Comment by teodord** [comment]
I'm not sure why the workaround would not work. I understand the users are not technical, but still, they seem to write raw HTML themselves.
If they do not write raw HTML themselves, it measn they are using some simple HTML editor that generates that HTML for them. It probably also means that the HTML they write is not put into the report directly, but rather comes from a database or some storage where some other application puts it. If the HTML comes from the report data, then all you need to do is to use an expression like the one above to automatically append the harmless tag before the HTML value they provided.

This workaround would not work only if the end users type in HTML into the report text element directly, probably using our own report design tool such as Jaspersoft Studio. If they do, then they are really writing raw HTML, because we do not have HTML editor for text fields in our report designer.
