### ISSUE TITLE
Protect Export Files

### ISSUE THREAD

**Issue by halimpuckjava** [TIBCOSoftware/jasperreports#391]
hi

1.  lock exporting files to any change
2.  add password to export files when exporting

**Comment by teodord** [comment]
Hi!

1. Once the JasperReports library has created an export document for you (I say document, not file, because the library might just output to an output stream and that is not necessarily a file. Think of web application streaming PDF on the HTTP response or about a PDF stored in a database BLOB), you are free to do whatever you want with it. 

I am not sure what locking an export file exactly means, but if you know what you expect from this feature, I'm sure you can achieve it from your own application, right after you store the JasperReports export output into a file. After all, we are talking about a library that is embedded into a Java application of your own. And in your own application, you can implement whatever additional features you need to protect your files.

2. We do have support for encrypted PDF, XLSX, DOCX, PPTX. You might want to read more documentation about these:
https://jasperreports.sourceforge.net/sample.reference/pdfencrypt/index.html#pdfencrypt
https://jasperreports.sourceforge.net/config.reference.html#net.sf.jasperreports.export.pdf.permissions.allowed
https://jasperreports.sourceforge.net/config.reference.html#net.sf.jasperreports.export.pdf.permissions.denied
https://jasperreports.sourceforge.net/config.reference.html#net.sf.jasperreports.export.docx.encryption.password
https://jasperreports.sourceforge.net/config.reference.html#net.sf.jasperreports.export.xls.encryption.password
https://jasperreports.sourceforge.net/config.reference.html#net.sf.jasperreports.export.pptx.encryption.password

If you have questions about JasperReports Library functionality, please post them on the public forums at:
https://community.jaspersoft.com/project/jasperreports-library/answers
where others could benefit from the answers you get.

Thank you,
Teodor
