### ISSUE TITLE
Backward incompatibility between 6.20.5 and 6.20.6

### ISSUE THREAD

**Issue by Canos** [TIBCOSoftware/jasperreports#406]
in 6.20.5 
the class `net.sf.jasperreports.engine.export.JRPdfExporter`
had a `protected PdfImage pxImage`
and also a `getPxImage()` method

these have disappeared in 6.20.6
I overrided this method to use a custom transparent pixel image.

Any recommendation?

Thanks

**Comment by teodord** [comment]
As the commit comment explains, the transparent image was removed here:
https://github.com/TIBCOSoftware/jasperreports/commit/5f2df8ec0ef7b9b0dd8c3990cc0f3786ce13f0c4
It was a trick that was no longer needed. Not sure why you needed to customise it, but since we are no longer using any transparent image, you probably don't need to override it anymore.
