### ISSUE TITLE
Group header/title band taking up at least a page leads to loss of variable values in specific cases.

### ISSUE THREAD

**Issue by SofieYesplan** [TIBCOSoftware/jasperreports#418]
See added zip file. An issue in which a variable loses its value when a group header band or title band takes up a whole page in combination with Split Type of the following detail band being set to "Prevent".
(We are currently working with version 6.20.3)

[group header taking up at least a page leads to loss of variable values.jrxml.zip](https://github.com/TIBCOSoftware/jasperreports/files/14178437/group.header.taking.up.at.least.a.page.leads.to.loss.of.variable.values.jrxml.zip)

**Comment by SofieYesplan** [comment]
Thanks for the reply Teodor! We did eventually fix it by using a parameter. In certain situations however, it is more difficult for us to go for parameters. When we make compositions it is often easier for us to work with variables that don't change instead of parameters as in the case of parameters we often have to introduce a whole lot of parameter bindings and it starts getting quite complex.

Either way, the variable losing its value just seemed like a bit strange behaviour so we wanted to mention it here. Yesplan has been working with JasperReports for 10+ years and we're very happy with it so we want to contribute to further helping it be as reliable as possible!

**Comment by teodord** [comment]
The case you described is indeed tricky and the reason I suggested you use a workaround is because I'm not sure we are going to try fix it as it is in a very delicate part of the program and any change would probably cause other regressions.

Using parameters with default value expression is in my opinion the best way for declaring "constant" values. There should be no difference between declaring a parameter or a variable with such behaviour. Not sure what you mean by "parameter binding", but parameters can simply be declared and used inside the current report/dataset, without being passed around.

**Comment by SofieYesplan** [comment]
Thanks for the explanation, we'll keep it in mind.
Just as an afterthought so that you are fully up to date with this issue: We tested it using a variable that changes value (Say, an integer variable `x` with initial value "0" with expression `$V{x}+1`) and the problem is the same, namely the variable loses its value and prints "null". Our main issue with it is that the null pointer exception gets absorbed by the Jaspersoft Studio so we are often unaware of the issue until it gets pointed out by a client of ours that the value is not being printed as expected in the report.
