### ISSUE TITLE
Unexpected whitespace in group header bands.

### ISSUE THREAD

**Issue by SofieYesplan** [TIBCOSoftware/jasperreports#419]
See added zip file.
Summary of issue:

We have a block of text that we print 10 times in a list (See dataset of list) in the group header band. As you can see when generating the report, this generates a random white line on page 2.

It only occurs when there is whitespace above and below the list, if we eliminate the whitespace, the issue does not occur.

[unexpected whitespace in group headers.jrxml.zip](https://github.com/TIBCOSoftware/jasperreports/files/14178509/unexpected.whitespace.in.group.headers.jrxml.zip)

**Comment by teodord** [comment]
I ran your report but I don't see any random white line. Maybe I'm not looking in the right place. Please attach a PDF or a screenshot indicating it.

**Comment by SofieYesplan** [comment]
Hi Teodor, here's a pdf generated from this file. We're working with version 6.20.3 so if you're not getting the white line then maybe this was fixed in the most recent 6.21?
[report6470815749729232900.pdf](https://github.com/TIBCOSoftware/jasperreports/files/14238903/report6470815749729232900.pdf)

**Comment by teodord** [comment]
The white space comes from your text element inside the list cell, which is 30 pixels tall.
These 30 pixels are more than what is needed for 2 rows of text that are left over on the new page, but the text element never shrinks. You just need to make the text element and its cell smaller. Maybe like 10 pixels, so that it always grows and never has to shrink.
I suggest that when making tests, you use opaque elements with coloured backgrounds and maybe borders so that you see from where the space comes from.

**Comment by SofieYesplan** [comment]
That seems logical indeed, thanks for the clear reply!
