### ISSUE TITLE
Vulnerable dependency commons-collections

### ISSUE THREAD

**Issue by danielpeintner** [TIBCOSoftware/jasperreports#424]
FYI: The IntelliJ IDE shows the following warning for the dependency `net.sf.jasperreports:jasperreports:6.21.2`

>  Provides transitive vulnerable dependency maven:commons-collections:commons-collections:3.2.2 Cx78f40514-81ff 7.5 Uncontrolled Recursion vulnerability with High severity found  Results powered by Checkmarx(c) 

see https://devhub.checkmarx.com/cve-details/Cx78f40514-81ff/

**Comment by teodord** [comment]
We are not familiar with the checkmarx.com CVE database. We are using an OWASP plugin to regularily check for CVEs and also Github has a scanner which raises CVE notifications for us on a regular basis.
The CVE you mentioned is from 2018 and did not surface yet on OWASP or Github, so we are going to ignore it for now.
There is nothing we can do about it anyway because Commons Collections 3 is required by Digester and we cannot upgrade or get rid of digester. At least not yet.
