### ISSUE TITLE
Internal JSS Console not appearing in JasperSoft Studio 6.21.2

### ISSUE THREAD

**Issue by tcleenewerck** [TIBCOSoftware/jasperreports#426]
I do not now where I can submit bugs for the studio version. So I'll post it here. The old bugtracker links that I used to work with are no longer working.

I've enabled the internal jss console in https://share.zight.com/9Zu4yzmX but it is not appearing in the console window https://share.zight.com/eDueEn0W . In Jasper Soft Studio 6.20.3 it is available like this https://share.zight.com/z8uBblQn .

**Comment by maxrabbi** [comment]
Hi the fix should be available in the next upcoming Jaspersoft Studio Community Edition.
I hope this helps. 

Regards,
Massimo.

P.S: Jaspersoft Studio tracker on Github is no longer available since the project was remove. You can try to use the Community one: https://community.jaspersoft.com/tracker/jaspersoft%C2%AE-studio/
I already reported internally some issues with it. I hope they will be solved soon. Thanks.
