### ISSUE TITLE
Do we have any option to pick .jasper file from classpath

### ISSUE THREAD

**Issue by tuspatil1** [TIBCOSoftware/jasperreports#428]
Hi Team,

We use `JasperFillManager.fillReport(String, Map<String,Object>, JRDataSource)` method to generate the jasperprint, where first argument is the path of ".jasper" file.

Do we have any alternative, where we can pick ".jasper" file from classpath/jars?

Thanks,
Tushar

**Comment by teodord** [comment]
There is the [JasperFillManager.fillReport(InputStream, Map<String, Object>, JRDataSource)](https://jasperreports.sourceforge.net/api/net/sf/jasperreports/engine/JasperFillManager.html#fillReport(java.io.InputStream,java.util.Map,net.sf.jasperreports.engine.JRDataSource)), which receives the *.jasper file as InputStream.
And you can get such InputStream from a *.jasper file in the classpath using [JRLoader.getResourceInputStream(String)](https://jasperreports.sourceforge.net/api/net/sf/jasperreports/engine/util/JRLoader.html#getResourceInputStream(java.lang.String)).

Since this is not a bug or request for enhancement, but rather a request for assistance, please post your questions on the public forums at:
https://community.jaspersoft.com/forums/
so that others could benefit from the answers you get.

Thank you,
Teodor

**Comment by tuspatil1** [comment]
Thanks Teodor for your prompt response.
Sure. From next time I will post such concerns on public forums.
