### ISSUE TITLE
Is this Java 11 ready? 

### ISSUE THREAD

**Issue by josepowera** [TIBCOSoftware/jasperreports#43]
We embed jasperreports as component. Can we use this with java 11 in runtime?

**Comment by teodord** [comment]
JasperReports works with Java 11. The project's build process is not yet adapted to Java 11, but the JARs that we publish work with Java 11. Have you tried it and it did not work for you?

**Comment by zeronius** [comment]
I'm not sure that JasperReports works properly with Java 11 because of Apache POI 3.15 dependency. POI has issues with Java 10 which were fixed in version 4.0.0. , see https://bz.apache.org/bugzilla/show_bug.cgi?id=62187 . Or at least JasperReports blocks using POI with Java 11, see https://github.com/TIBCOSoftware/jasperreports/issues/46 .

**Comment by teodord** [comment]
While we are indeed going to try upgrade to POI 4+, the problem you mentioned about POI 3.15 and Java 10 does not seem to affect JasperReports. Probably because we are not using that functionality of POI which has the problem. If you try the latest version from our master branch and run all the samples and tests, you can see they are not failing when using POI 3.15.

**Comment by asfernandes** [comment]
Isn't Java 11 already supported in the latest version? Shouldn't this issue be closed?

**Comment by teodord** [comment]
POI was upgraded to 4.0.1 and now Javaflow also supports Java 11.

**Comment by asfernandes** [comment]
Now waiting for Jasper Studio support Java 11...
