### ISSUE TITLE
Error generating QRCode using Barcode4J in JasperReport v7

### ISSUE THREAD

**Issue by wahyubaskara** [TIBCOSoftware/jasperreports#456]
I cannot create QRCode after using JasperReport v7

<img width="1433" alt="1" src="https://github.com/TIBCOSoftware/jasperreports/assets/17234155/965645b1-10f5-425b-8130-3bc685fe4bc3">
<img width="1434" alt="2" src="https://github.com/TIBCOSoftware/jasperreports/assets/17234155/ec280a0c-1039-4776-bc47-998a6ed2200c">
<img width="1434" alt="3" src="https://github.com/TIBCOSoftware/jasperreports/assets/17234155/887fe96a-7cf3-4518-ba0d-fbaa4ca84851">
<img width="1431" alt="4" src="https://github.com/TIBCOSoftware/jasperreports/assets/17234155/aa293f95-f26c-4b78-8637-9f618ecffec9">

**Comment by teodord** [comment]
Yes, there is a bug in this latest release. To workaround it, right-click the barcode element, go to Properties view and in the Barcode tab select one of the options inside Error Correction Level property. Pick the L value, which is also the default.

This will be fixed in a subsequent release soon.

I hope this helps.
Teodor

**Comment by vanicekv** [comment]
Hello,

I have the same problem and it's a lot of reports. When are you planning to release the patch please?

Thank you.

**Comment by teodord** [comment]
It could take a few weeks. We do not have a target date. Maybe you can stay with version 6 for now.

Thank you,
Teodor

**Comment by vanicekv** [comment]
That's a shame, such a simple fix...

**Comment by teodord** [comment]
As you can see from above comment, the fix is already pushed here at Github. 
A snapshot containing the fix from master branch is available at:
https://jaspersoft.jfrog.io/ui/native/jr-ce-snapshots/net/sf/jasperreports/jasperreports/master-SNAPSHOT/

You should probably stay with previous version. Don't see why the rush to upgrade to 7.

Thank you,
Teodor

**Comment by vanicekv** [comment]
Thanks for providing the snapshot, it's up and running now.
