### ISSUE TITLE
JasperReports 6.x vs 7.x Series [Community Edition]

### ISSUE THREAD

**Issue by tuspatil1** [TIBCOSoftware/jasperreports#500]
Hi Team,

To the best of our knowledge, the 7.x version introduces significant changes, and as users, we would need to make several changes in our application to ensure compatibility with 7.x.

Please let us know, if we are sufficing our requirements with 6.x version, then can we ignore upgrading to 7.0.x.

Additionally, will TIBCO continue to maintain both the 6.x and 7.x series in parallel for bug fixes?

Thanks,
Tushar

**Comment by teodord** [comment]
Hi,

Since you posted on the Community Edition page of our project, I can tell you what the future of JRL CE would be:

For JasperReports CE version, we never fix older versions. Every fix is delivered with a new release. We never look back or go back when it comes to CE releases like the ones you see here at Github.

A special case was for version 6.21.4, which is the only public CE "old" release that we have made after publishing 7.0.0.
Chances are there will be no more 6.21.x in the future, unless some terrible bug is found, which is unlikely at this point.

If you are a Jaspersoft customer, then you'll receive support and patches according to the contract you have with Jaspersoft.

Thank you,
Teodor
