### ISSUE TITLE
Column number 69 out of range: the DOCX format does not support more than 63 columns in a table.

### ISSUE THREAD

**Issue by abhijithmadu** [TIBCOSoftware/jasperreports#503]
Hi,
Facing this issue in Docx Format. 
Actually the document format issue came in my latest version of MS word that time I am using this property
`<property name="net.sf.jasperreports.export.docx.frames.as.nested.tables" value="false"/>`
after that I am getting the error like this . Please help to solve this problem. 
![image](https://github.com/user-attachments/assets/0a059a3e-558d-49f0-8f27-d765828d69e4)

**Comment by abhijithmadu** [comment]
@teodord Can you help me to solve this issue please

**Comment by teodord** [comment]
If you do not actually have that many columns in your report content, it means most of the columns are created just for arranging elements on the page according to your design.
Without seeing your report template, I can only assume that there are many little columns in the layout simply because your elements do not align perfectly with each other causing the engine to create spacing columns to reproduce exactly the layout you designed.

The solution is to make sure your elements align as much as possible with each other.

I hope this helps.
Teodor
