### ISSUE TITLE
Add firstPageFooter

### ISSUE THREAD

**Issue by polybas** [TIBCOSoftware/jasperreports#9]
The page footer section to use on the first page instead of the normal page footer. This might not be the very next page of the document in case the summary section is also present. This section is sometimes useful when summary information has to be displayed at the bottom of the first page.

It's like lastPageFooter but only in first page

**Comment by teodord** [comment]
Not sure exactly what you mean, but for the first page, we don't face the same problem as with a last page, which required a special report section for the lastPageFooter.

The content of a page footer can be displayed conditionally using a printWhenExpression in which we check for PAGE_NUMBER variable to be 1.
So it is fairly easy to display something conditionally only on the first page.

Unlike with the first page, which is easy to detect, as explained above, we had to introduce a special section for lastPageFooter because the last page cannot be detected through a variable. We don't know a page is the last page of the report until the report actually finishes, at which point it is too late to do anything about it.

**Comment by tiagowippel** [comment]
Sorry to come back to this... 

I am designing a report which prints the footer only in the first page. (using the printWhenExpression verifying the PAGE_NUMBER). It works, but all the sequential page, I have a white space on footer local...

Is there a way to avoid that behavior?

**Comment by polybas** [comment]
I get source and add firstPageFooter by myself.
