### ISSUE TITLE
Expression support should default to JDK8 compatibility

### ISSUE THREAD

**Issue by ShaheedHaque** [TIBCOSoftware/jasperreports#98]
Now that Java pre-JDK8 has fallen out of support, is there any real downside to making expression support default to JDK8 compatibility?

That would make [this tweak on Stackoverflow](https://stackoverflow.com/questions/41618362/use-lambda-expressions-inside-textfield-expression-in-jaspersoft-studio-6-3) unnecessary, and also solve [my problem](https://community.jaspersoft.com/questions/1112516/trouble-enabling-lambda-support) with any luck.

**Comment by dadza** [comment]
JasperReports defaults to Java 8 compilation since version 6.6.0 (when the Eclipse JDT/ECJ report compiler is used), see https://github.com/TIBCOSoftware/jasperreports/commit/951944d255fe48e13034d11f8c299c0aa1443233

I don't know if there's a problem specific to Jaspersoft Studio.  Try the latest Studio version, and if it doesn't work log a bug for Jaspersoft Studio at https://github.com/TIBCOSoftware/jaspersoft-studio-ce
